# Generated by Django 6.0.7 on 2026-08-03 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='名称')),
                ('name_kana', models.CharField(blank=True, max_length=160, verbose_name='よみ')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
                ('ward', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='区市町村')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='経度')),
                ('smoking_status', models.CharField(choices=[('none', '喫煙不可'), ('heated_only', '加熱式のみ可'), ('cigarette_only', '紙巻きのみ可'), ('both', '両方可')], db_index=True, max_length=20, verbose_name='喫煙区分（練習用ダミー）')),
                ('website', models.URLField(blank=True, max_length=300, verbose_name='公式サイト')),
                ('osm_id', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='OSM ID')),
                ('data_source', models.CharField(choices=[('osm_overpass', 'OpenStreetMap (Overpass API)'), ('gsi_reverse', '国土地理院 逆ジオコーディング'), ('manual', '手入力')], default='osm_overpass', max_length=20, verbose_name='座標の出所')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '図書館',
                'verbose_name_plural': '図書館',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='idx_library_latlng')],
                'constraints': [models.UniqueConstraint(fields=('name', 'latitude', 'longitude'), name='uniq_library_spot')],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='libraries.library')),
            ],
            options={
                'verbose_name': 'お気に入り',
                'verbose_name_plural': 'お気に入り',
                'constraints': [models.UniqueConstraint(fields=('user', 'library'), name='uniq_user_library')],
            },
        ),
    ]
